version: 1.0.{build}
install:
  - choco install dart-sdk
  - ps: refreshenv
  - dart --version
  - pub global activate stagehand 1.0.18
  - ps: pwd
  - pub get

build: off
test_script:
  - pub run test
