version: 1.0.{build}
install:
  - choco install dart-sdk
  - ps: refreshenv
  - refreshenv
  - set pub_util_test_path=c:\tools\dart-sdk\bin
  - ps: pwd
  - pub get

build: off
test_script:
  - pub run test
