name: pub_util
description: Utility to manage globally installed packages
author: Kulshekhar Kabra <kulshekhar+dart@gmail.com>
version: 0.0.3
homepage: https://github.com/kulshekhar/pub_util.dart

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  args: ">=0.13.7"
  http: ">=0.11.3"

dev_dependencies:
  test: ">=0.12.17"

executables:
  pub_util:
